export const Colors=[
    {
        name:'red_700',
        data:{
            primary:{
                base:'#d32f2f',light:'#ff6659',dark:'#9a0007'
            },
            normal:{
                light:'white',dark:'black'
            }
        }
    },
    {
        name:'pink_600',
        data:{
            primary:{
                base:'#d81b60',light:'#ff5c8d',dark:'#a00037'
            },
            normal:{
                light:'white',dark:'black'
            }
        }
    }, 
    {
        name:'purple_400',
        data:{
            primary:{
                base:'#ab47bc',light:'#df78ef',dark:'#790e8b'
            },
            normal:{
                light:'white',dark:'black'
            }
        }
    }, 
    {
        name:'deep_purple_400',
        data:{
            primary:{
                base:'#7e57c2',light:'#b085f5',dark:'#4d2c91'
            },
            normal:{
                light:'white',dark:'black'
            }
        }
    },
    {
        name:'grey_800',
        data:{
            primary:{
                base:'#424242',light:'#6d6d6d',dark:'#1b1b1b'
            },
            normal:{
                light:'white',dark:'black'
            }
        }
    }
];